# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CatalystApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CatalystApp
  pod 'Mux-Stats-AVPlayer', :path => '../../'
  
  target 'CatalystAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CatalystAppUITests' do
    # Pods for testing
  end

end
