agents:
  queue: "macOS-Monterey-12-4"

steps:
  - command: "./scripts/unit-test-package.sh"
    label: ":xcode_simulator: Unit Test Package"
    artifact_paths:
      - ".build/artifacts/*.xcresult.zip"
  - command: "./scripts/build-package.sh"
    label: ":xcode: Build Package"
    artifact_paths:
      - ".build/artifacts/*.xcresult.zip"
  - wait
  - command: "./scripts/version-check.sh"
    label: ":clipboard: Validate Version Metadata"
    branches: "releases/*"
  - wait
  - command: "./scripts/run-tests-swift-package-manager-ventura.sh build-only"
    label: ":swift: Build Swift Package Manager Example"
    branches: "!releases/*"
  - command: "./scripts/run-tests-swift-package-manager-ventura.sh"
    label: ":swift: Test Swift Package Manager Example"
    branches: "releases/*"
  - wait
  - command: "./scripts/run-tests-cocoapods-ventura.sh build-only"
    label: ":cocoapods: Build Cocoapods Example"
    branches: "!releases/*"
  - command: "./scripts/run-tests-cocoapods-ventura.sh"
    label: ":cocoapods: Test Cocoapods Example"
    branches: "releases/*"
  - wait
  - command: "./scripts/validate-podspec.sh"
    label: ":cocoapods: Validate Podspec"
