# Uncomment the next line to define a global platform for your project

target 'MUXSDKStats' do
  platform :ios, '11.0'
  use_frameworks!
  # Pods for MUXSDKStats
  pod 'Mux-Stats-Core', '~> 4.5'
  
  target 'MUXSDKStatsTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Mux-Stats-Core', '~> 4.5'
  end
  
end

target 'MUXSDKStatsTv' do
  platform :tvos, '11.0'
  use_frameworks!
  # Pods for MUXSDKStatsTv
  pod 'Mux-Stats-Core', '~> 4.5'
end
