# Uncomment the next line to define a global platform for your projec

target 'MUXSDKStats' do
  platform :ios, '9.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  use_frameworks!(:linkage => :static)

  # Pods for MUXSDKStats
  pod 'Mux-Stats-Core', '~>3.0'
  

  target 'MUXSDKStatsTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Mux-Stats-Core', '~>3.0'
  end

end

target 'MUXSDKStatsTv' do
  platform :tvos, '9.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MUXSDKStatsTv
  pod 'Mux-Stats-Core', '~>3.0'
end
