platform :tvos, '12.0'

target 'TvDemoApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for TvDemoApp
  pod 'Mux-Stats-AVPlayer'
  pod 'Mux-Stats-Google-IMA'
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['TVOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
    project.build_configurations.each do |config|
        config.build_settings['TVOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
