# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TvDemoApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for TvDemoApp
  # pod 'Mux-Stats-AVPlayer', '~> 2.0'
  pod 'Mux-Stats-AVPlayer', :path => '../../'

  pod 'GoogleAds-IMA-tvOS-SDK', '~> 4.2'
  # pod 'Mux-Stats-Google-IMA', '~> 0.6
  pod 'Mux-Stats-Google-IMA', :git => 'https://github.com/muxinc/mux-stats-google-ima.git', :branch => 'dj/xcframework-dependencies'
end
