target 'TvDemoApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for TvDemoApp
  # pod 'Mux-Stats-AVPlayer', '~> 2.0'
  pod 'Mux-Stats-AVPlayer', :path => '../../'
  pod 'Mux-Stats-Core', :git => 'https://github.com/muxinc/stats-sdk-objc.git', :branch => 'bmulligan/customerdata-without-customerviewerdata'
  pod 'GoogleAds-IMA-tvOS-SDK', '~> 4.2'
  pod 'Mux-Stats-Google-IMA', '~> 0.6'
end
