name: Build

on:
  push:

jobs:
  build:
    name: Run unit tests and build the SDK
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Unit Tests"
        run: ".buildkite/unit-tests-big-sur.sh"
      - name: "🔨 Build"
        run: ".buildkite/build.sh"
      - name: "Upload framework artifact"
        uses: actions/upload-artifact@v2
        with: 
          name: "MUXSDKStats.xcframework.zip"
          path: "MUXSDKStats.xcframework.zip"
  tests:
    name: Test the SDK with a Demo App
    needs: build
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download framework artifact
        uses: actions/download-artifact@v2
        with:
          name: "MUXSDKStats.xcframework.zip"
      - name: Run tests
        run: "apps/DemoApp/run-tests-big-sur.sh"
