name: Validate release

on:
  push:
    branches:
      - 'releases/**'

jobs:
  version-check:
    runs-on: macos-13
    name: Validate Versions
    steps:
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_15.0.1.app/Contents/Developer'
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run Version Check Script
        run: ./scripts/version-check.sh Mux-Stats-AVPlayer.podspec MUXSDKStats.json
  validate-podspec:
    name: Validate Podspec
    runs-on: macos-13
    steps:
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_15.0.1.app/Contents/Developer'
      - name: Install xcbeautify
        run: brew install xcbeautify
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Validate Podspec"
        run: "scripts/validate-podspec.sh"
  validate-carthage:
    name: Validate Carthage
    runs-on: macos-13
    steps:
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_15.0.1.app/Contents/Developer'
      - name: Install xcbeautify
        run: brew install xcbeautify
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Validate Carthage Build"
        run: "scripts/validate-carthage.sh"
  unit-test-ventura:
    runs-on: macos-13
    name: Complete Unit Test Pass on macOS Ventura
    steps:
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_15.0.1.app/Contents/Developer'
      - name: Install xcbeautify
        run: brew install xcbeautify
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run Complete Unit Test Pass
        run: ./scripts/run-complete-unit-test-pass-ventura.sh
  unit-test-monterey:
    runs-on: macos-12
    name: Complete Unit Test Pass on macOS Monterey
    steps:
      - name: Install xcbeautify
        run: brew install xcbeautify
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run Complete Unit Test Pass
        run: ./scripts/run-complete-unit-test-pass-monterey.sh
