apiVersion: v1alpha
kind: xctest
showConsoleLog: false
sauce:
  region: us-west-1
  concurrency: 3
XCTest:
  app: .build/MUXSDKStats-iOS.xctestproducts/Tests/0/Debug-iphoneos/IntegrationTestHost.app
  xcTestRunFile: .build/MUXSDKStats-iOS.xctestproducts/Tests/0/CIPipeline.xctestrun
  otherApps:
  - .build/MUXSDKStats-iOS.xctestproducts/Tests/0/Debug-iphoneos/UITests-Runner.app
  - .build/MUXSDKStats-iOS.xctestproducts/Tests/0/Debug-iphoneos/UnitTestsHost.app
suites:
- name: iOS 26
  devices:
  - name: .*
    platformVersion: 26.*
