# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'video-demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # pod 'Mux-Stats-AVPlayer', '~> 2.0'
  pod 'Mux-Stats-AVPlayer', :path => '../../'

  pod 'GoogleAds-IMA-iOS-SDK', '~> 3.9'
#  pod 'Mux-Stats-Google-IMA', '~> 0.6'
  pod 'Mux-Stats-Google-IMA', :git => 'https://github.com/muxinc/mux-stats-google-ima.git', :branch => 'dj/xcframework-dependencies'
end
