platform :ios, '13.0'

target 'video-demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Mux-Stats-AVPlayer', :path => '../../'
  pod 'GoogleAds-IMA-iOS-SDK', '~> 3.9'
  pod 'Mux-Stats-Google-IMA', '~> 0.6'
end
